(define (counting-change amount denoms)
	(define (greatest denoms)
	  (cond ((= denoms 5) 50)
		((= denoms 4) 25)
		((= denoms 3) 10)
		((= denoms 2) 5)
		((= denoms 1) 1)))
	(cond ((= amount 0) 1)
	      ((or (< amount 0) (= denoms 0)) 0)
	      (else (+ (counting-change amount (- denoms 1))
		      (counting-change (- amount (greatest denoms)) denoms)))))
